[project]
name = "genai"
version = "0.1.0"
description = "A personal intelligent retrieval system combining legal knowledge base and generative AI"
readme = "README.md"
requires-python = ">=3.12, <3.13"
dependencies = [
    "chromadb>=1.4.0",
    "fastapi[standard]>=0.128.0",
    "sentencepiece>=0.2.1",
    "transformers>=4.57.3",
    "torch",
    "torchvision",
    "accelerate>=1.12.0",
    "sentence-transformers>=5.2.0",
    "unsloth",
    "sqlmodel>=0.0.31",
]

[tool.uv.sources]
torch = { index = "pytorch-cu130" }
torchvision = { index = "pytorch-cu130" }

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
